version: 2
updates:
  # Enable version updates for Docker (from docker-compose.yml)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Dockerfiles inside /src
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"

  # Explicitly disable pip updates for /src
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
    # This prevents Dependabot from creating PRs
    open-pull-requests-limit: 0

  # Enable version updates for uv (pyproject.toml)
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    # Adding some settings to increase visibility
    open-pull-requests-limit: 20
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "build"
      include: "scope"

  # Enable version updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
