[project]
name = "feluda-video-hashing"
version = "0.1.0"
description = "A Python operator for generating video perceptual hashes using TMK+PDQF."
requires-python = ">=3.8"
dependencies = [
    "base64",  # For encoding binary hash data
    "ffmpeg-python>=0.2.0",  # Python wrapper for FFmpeg
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.semantic_release]
version_variable = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "main"
prerelease = false
tag_format = "{name}-{version}"

[tool.hatch.build.targets.wheel]
packages = ["."]
